name: WordPress Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: PHP Lint & WordPress Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, php-cs-fixer, phpcs
          extensions: mbstring, xml

      - name: Install PHPCS and WPCS
        run: |
          composer global require wp-coding-standards/wpcs
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHPCS
        run: phpcs --standard=WordPress --ignore=vendor ./
